In [ ]:
#CountVectorizer
d1="I love programming"
d2="Programming is interesting"
d3="I love pizza very very much"
var=["I","love","Programming","is","very","interesting","much","pizza"]
d1=[1,1,1,0,0,0,0,0]
d2=[0,0,0,1,0,1,0,0]
d3=[1,1,0,0,2,0,1,1]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
d1="I love programming"
d2="Programming is interesting"
d3="I love pizza very very much"
documents=[d1,d2,d3]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(documents)
print(vectorizer.vocabulary_)
print(X.toarray())


{'love': 2, 'programming': 5, 'is': 1, 'interesting': 0, 'pizza': 4, 'very': 6, 'much': 3}
[[0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0]
 [0 0 1 1 1 0 2]]


In [8]:
import pandas as pd
import numpy as np
import matplotlib as plt
df=pd.read_csv("Downloads/newsgroups_train.csv")

print(df)

                                                   text  target       category
0     From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1     From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2     From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3     From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4     From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space
...                                                 ...     ...            ...
1652  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
1653  From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...       1  comp.graphics
1654  From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...       2      sci.space
1655  From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2      sci.space
1656  From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...       2      sci.space

[1657 rows x 3 columns]


In [9]:
import pandas as pd
import numpy as np
import matplotlib as plt
df=pd.read_csv("Downloads/newsgroups_test.csv")

print(df)

                                                   text  target       category
0     From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1     From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2     From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3     From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4     From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
...                                                 ...     ...            ...
1097  From: malek@pi.titech.ac.jp (Zidouri Abdelmale...       1  comp.graphics
1098  From: livesey@solntze.wpd.sgi.com (Jon Livesey...       0    alt.atheism
1099  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...       0    alt.atheism
1100  From: beck@irzr17.inf.tu-dresden.de (Andre Bec...       1  comp.graphics
1101  From: 18084TM@msu.edu (Tom)\nSubject: Billboar...       2      sci.space

[1102 rows x 3 columns]


In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt
df=pd.read_csv("Downloads/nlp_test.csv")

print(df)

                                                   text  target  \
0     I am a little confused on all of the models of...       7   
1     I'm not familiar at all with the format of the...       5   
2                                   \nIn a word, yes.\n       0   
3     \nThey were attacking the Iraqis to drive them...      17   
4     \nI've just spent two solid months arguing tha...      19   
...                                                 ...     ...   
7527  \n   Henry, if I read you correctly, you may b...      14   
7528  about\nthem on\n\nActually, I thought Macs wer...       4   
7529  I sent a version of this post out a while ago,...       9   
7530  I have this kit which includes the following :...       6   
7531  \nFine, but one of the points of this entire d...      15   

                    category  
0                  rec.autos  
1             comp.windows.x  
2                alt.atheism  
3      talk.politics.mideast  
4         talk.religion.misc  
...      

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
df=pd.read_csv("Downloads/nlp_train.csv")

print(df)

                                                    text  target  \
0      I was wondering if anyone out there could enli...       7   
1      A fair number of brave souls who upgraded thei...       4   
2      well folks, my mac plus finally gave up the gh...       4   
3      \nDo you have Weitek's address/phone number?  ...       1   
4      From article <C5owCB.n3p@world.std.com>, by to...      14   
...                                                  ...     ...   
11309  DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...      13   
11310  I have a (very old) Mac 512k and a Mac Plus, b...       4   
11311  I just installed a DX2-66 CPU in a clone mothe...       3   
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1   
11313  Stolen from Pasadena between 4:30 and 6:30 pm ...       8   

                       category  
0                     rec.autos  
1         comp.sys.mac.hardware  
2         comp.sys.mac.hardware  
3                 comp.graphics  
4            

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
from sklearn.datasets import fetch_20newsgroups

# Load the full 20 Newsgroups dataset
newsgroups_data = fetch_20newsgroups(subset='all')


In [ ]:
from sklearn.datasets import fetch_20newsgroups

# Load only the training subset
newsgroups_train = fetch_20newsgroups(subset='train')


In [ ]:
from sklearn.datasets import fetch_20newsgroups

# Load only the training subset
newsgroups_train = fetch_20newsgroups(subset='test')


In [ ]:
# Show the first 5 documents and their corresponding target category
for i in range(5):
    print(f"\nDocument {i+1}:\n{'-'*40}")
    print(newsgroups_train.data[i][:500])  # Print first 500 characters for brevity
    print(f"\nCategory: {newsgroups_train.target_names[newsgroups_train.target[i]]}")


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the training data
X_train_tfidf = vectorizer.fit_transform(newsgroups_train.data)

# Optionally, transform the test data too if you're doing classification later
X_test_tfidf = vectorizer.transform(newsgroups_test.data)
